/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type InquiryId = bigint;
export interface Property {
  'id' : PropertyId,
  'title' : string,
  'featured' : boolean,
  'propertyType' : PropertyType,
  'bedrooms' : [] | [bigint],
  'description' : string,
  'amenities' : Array<string>,
  'builderTag' : string,
  'areaSqft' : bigint,
  'bathrooms' : [] | [bigint],
  'price' : string,
  'location' : string,
}
export type PropertyId = bigint;
export type PropertyType = { 'commercial' : null } |
  { 'villa' : null } |
  { 'plot' : null } |
  { 'apartment' : null };
export type SubmitInquiryResult = { 'ok' : InquiryId } |
  { 'err' : string };
export interface _SERVICE {
  'getFeaturedProperties' : ActorMethod<[], Array<Property>>,
  'getProperties' : ActorMethod<[], Array<Property>>,
  'getProperty' : ActorMethod<[PropertyId], [] | [Property]>,
  'submitInquiry' : ActorMethod<
    [string, string, string, string, [] | [PropertyId]],
    SubmitInquiryResult
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];