/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PropertyId = IDL.Nat;
export const PropertyType = IDL.Variant({
  'commercial' : IDL.Null,
  'villa' : IDL.Null,
  'plot' : IDL.Null,
  'apartment' : IDL.Null,
});
export const Property = IDL.Record({
  'id' : PropertyId,
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'propertyType' : PropertyType,
  'bedrooms' : IDL.Opt(IDL.Nat),
  'description' : IDL.Text,
  'amenities' : IDL.Vec(IDL.Text),
  'builderTag' : IDL.Text,
  'areaSqft' : IDL.Nat,
  'bathrooms' : IDL.Opt(IDL.Nat),
  'price' : IDL.Text,
  'location' : IDL.Text,
});
export const InquiryId = IDL.Nat;
export const SubmitInquiryResult = IDL.Variant({
  'ok' : InquiryId,
  'err' : IDL.Text,
});

export const idlService = IDL.Service({
  'getFeaturedProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  'getProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  'getProperty' : IDL.Func([PropertyId], [IDL.Opt(Property)], ['query']),
  'submitInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(PropertyId)],
      [SubmitInquiryResult],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PropertyId = IDL.Nat;
  const PropertyType = IDL.Variant({
    'commercial' : IDL.Null,
    'villa' : IDL.Null,
    'plot' : IDL.Null,
    'apartment' : IDL.Null,
  });
  const Property = IDL.Record({
    'id' : PropertyId,
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'propertyType' : PropertyType,
    'bedrooms' : IDL.Opt(IDL.Nat),
    'description' : IDL.Text,
    'amenities' : IDL.Vec(IDL.Text),
    'builderTag' : IDL.Text,
    'areaSqft' : IDL.Nat,
    'bathrooms' : IDL.Opt(IDL.Nat),
    'price' : IDL.Text,
    'location' : IDL.Text,
  });
  const InquiryId = IDL.Nat;
  const SubmitInquiryResult = IDL.Variant({
    'ok' : InquiryId,
    'err' : IDL.Text,
  });
  
  return IDL.Service({
    'getFeaturedProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
    'getProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
    'getProperty' : IDL.Func([PropertyId], [IDL.Opt(Property)], ['query']),
    'submitInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(PropertyId)],
        [SubmitInquiryResult],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };